bootstrap: Don't auto-install on Mac
Signed-off-by: Zack Cerza <zack@redhat.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -127,11 +127,18 @@ Darwin)
         echo "You need Homebrew: http://brew.sh/"
         exit 1
     fi
-    for keg in python libvirt libev libffi; do
+    for keg in python libvirt libev libffi notapackage; do
         if brew list $keg >/dev/null 2>&1; then
             echo "Found $keg"
         else
-            brew install $keg
+            if [ "$install" = true ]; then
+                brew install $keg
+            else
+                missing="${missing:+$missing }$keg"
+                echo "Please install missing packages or run './bootstrap install':"
+                echo "brew install $missing"
+                exit 1
+            fi
         fi
     done
     ;;
